# Generated by Django 5.2.4 on 2025-07-30 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icfes', '0002_exam_questions_alter_answer_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='icfes.exam')),
            ],
        ),
    ]
